name: CI

on:
  push:
    branches:
      - '**'
      - '!master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Install Python/Pip
        run: |
          sudo apt-get install python python-pip
          sudo pip install virtualenv

      - name: Mount Cache
        uses: actions/cache@v1
        with:
          path: "/home/runner/.cache/bazel"
          key: bazel

      - name: Install grcov
        run: |
          curl -sLO "https://github.com/mozilla/grcov/releases/download/v0.5.15/grcov-linux-x86_64.tar.bz2"
          bunzip2 grcov-linux-x86_64.tar.bz2
          tar -xzvf grcov-linux-x86_64.tar
          mkdir -p "${GITHUB_WORKSPACE}/bin/"
          mv grcov "${GITHUB_WORKSPACE}/bin/grcov"
          chmod +x "${GITHUB_WORKSPACE}/bin/grcov"

      - name: Install Bazelisk
        run: |
          curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.1.0/bazelisk-linux-amd64"
          mkdir -p "${GITHUB_WORKSPACE}/bin/"
          mv bazelisk-linux-amd64 "${GITHUB_WORKSPACE}/bin/bazel"
          chmod +x "${GITHUB_WORKSPACE}/bin/bazel"

      - name: Build & Test
        run: |
          make build test CI=yes VERBOSE=yes

      - name: Generate Coverage
        run: |
          cd "${GITHUB_WORKSPACE}/"
          curl -L https://github.com/ulfjack/coveragepy/archive/lcov-support.tar.gz | tar xvz
          "${GITHUB_WORKSPACE}/bin/bazel" coverage -t- --instrument_test_targets --experimental_cc_coverage \
              --test_output=errors --linkopt=--coverage --linkopt=-lc \
              --test_env=PYTHON_COVERAGE=${GITHUB_WORKSPACE}/coveragepy-lcov-support/__main__.py \
              --define=config_file=test //pytests:tests
        env:
          CC: clang-9

      - name: codecov
        if: always()
        run: |
          set -x
          cd "${GITHUB_WORKSPACE}/src"
          ~/bin/grcov coverage.py.info dist/Python/_coverage/ -t lcov \
            --ignore "external/*" --ignore "/usr/*" \
            --ignore "*deps_*" --ignore "*_pb2.py"  \
            --llvm > lcov.py.info
          sed -i 's/SF:.*test\.runfiles\/ocpy\/pytests/SF:ocpy\/pytests/g' coverage.py.info
          cd ..
          echo "Would upload";
          #bash -x <(curl -s https://codecov.io/bash) -Z -v -f src/lcov.py.info -F python_tests
        env:
          CC: clang-9
          #CODECOV_TOKEN: ${{ secrets.CODE_COV }}
