name: CI

on:
  push:
    branches:
      - '**'
      - '!master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Install Python/Pip
        run: |
          sudo apt-get install python python-pip
          sudo pip install virtualenv

      - name: Mount Cache
        uses: actions/cache@v1
        with:
          path: "/home/runner/.cache/bazel"
          key: bazel

      - name: Install Bazelisk
        run: |
          curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.1.0/bazelisk-linux-amd64"
          mkdir -p "${GITHUB_WORKSPACE}/bin/"
          mv bazelisk-linux-amd64 "${GITHUB_WORKSPACE}/bin/bazel"
          chmod +x "${GITHUB_WORKSPACE}/bin/bazel"

      - name: Build & Test
        run: |
          make build test CI=yes VERBOSE=yes

      - name: Generate Coverage
        run: |
          cd "${GITHUB_WORKSPACE}/"
          curl -L https://github.com/ulfjack/coveragepy/archive/lcov-support.tar.gz | tar xvz
          "${GITHUB_WORKSPACE}/bin/bazel" coverage -t- --instrument_test_targets --experimental_cc_coverage \
              --test_output=errors --linkopt=--coverage --linkopt=-lc \
              --test_env=PYTHON_COVERAGE=${GITHUB_WORKSPACE}/coveragepy-lcov-support/__main__.py \
              --define=config_file=test //pytests:tests
          # Unfortunately, coverage does not produce the hit information. Running
          # the compiled tests explicitly seems to work though.
          find dist/bin/pytests/ -maxdepth 1 -regex ".*-test$" -exec {} \;
          cp bazel-out/k8-fastbuild/testlogs/pd3/pytests/smoke-test/coverage.dat coverage.py.info
        env:
          CC: clang-9

      - name: Upload to Codecov
        if: always()
        run: |
          set -x
          cd "${GITHUB_WORKSPACE}/"
          "${GITHUB_WORKSPACE}/bin/grcov" coverage.py.info dist/bin/pytests/_objs/ -t lcov \
            --ignore "external/*" --ignore "/usr/*" \
            --ignore "*deps_*" --ignore "*_pb2.py"  \
            --llvm > lcov.py.info
          sed -i 's/SF:.*test\.runfiles\/pytests\/python/SF:pytests/g' coverage.py.info
          cd ..
          bash -x <(curl -s https://codecov.io/bash) -Z -v -f src/lcov.py.info -F python_tests
        env:
          CC: clang-9
          CODECOV_TOKEN: ${{ secrets.CODE_COV }}
